name: carbon
description: A carbon application
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  dropdown_button2: ^1.9.3
  flutter_svg: any
  image_picker: ^0.8.6+3
  iconify_flutter: ^0.0.4
  floating_bottom_navigation_bar: ^1.5.2
  scaled_list: ^2.0.0
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_inset_box_shadow: ^1.0.8
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  intl: any
  uuid: ^3.0.7
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  confetti: ^0.7.0
  syncfusion_flutter_charts: ^21.2.8
  sleek_circular_slider: ^2.0.1
  graphic: ^2.2.0
  fl_chart: ^0.62.0
  circular_seek_bar: ^1.1.0
  shimmer: ^3.0.0
  lottie: ^2.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
